### ISSUE TITLE
Adding .NET Core to the Ubuntu builds

### ISSUE THREAD

**Issue by braunsonm** [JetBrains/teamcity-docker-agent#11]
Are their plans to add .NET Core to the Ubuntu images? Seems to make sense to allow the build there as well.

**Comment by braunsonm** [comment]
Thank you @dtretyakov is this resolved?

**Comment by dtretyakov** [comment]
@ChaosCA, it will be available in the next version of TeamCity docker images.

**Comment by dtretyakov** [comment]
@ChaosCA, new images were pushed to docker hub
