### ISSUE TITLE
Update docker-engine

### ISSUE THREAD

**Issue by lorddaedra** [JetBrains/teamcity-docker-agent#12]
Please, update Docker. Your current version is outdated (little) and doesn't support commands like ```cat /data/teamcity_agent/conf/gcloud.service-key | docker login -u _json_key  --password-stdin https://gcr.io```

**Comment by lorddaedra** [comment]
( --password-stdin  )

**Comment by lorddaedra** [comment]
@shkate I see, you are maintainer of Dockerfile, can you update Docker from `17.06.0~ce-0~ubuntu` to `17.12.0~ce-0~ubuntu`, please? Looks like it's latest version of Docker, available to Ubuntu LTS.

Here https://github.com/JetBrains/teamcity-docker-agent/blob/master/ubuntu/Dockerfile#L21

**Comment by mykolapolonskyi** [comment]
this issue https://github.com/docker/for-mac/issues/1827 also can be additional reason to update the 17.06.0-ce 
(have catch it when set up teamcity and trying integrate in with local docker registry)

**Comment by VladRassokhin** [comment]
Hopefully would be in 2017.2.2

**Comment by johnkors** [comment]
@VladRassokhin I couldn´t really find in YouTrack whether this was resolved in a release. Has the engine been updated lately?

**Comment by VladRassokhin** [comment]
@johnkors  Last update was in March https://github.com/JetBrains/teamcity-docker-agent/commit/f4010b1bae9658890b0a37e527743e062c4058be
