### ISSUE TITLE
Examples for SERVER_URL

### ISSUE THREAD

**Issue by gaydenko** [JetBrains/teamcity-docker-agent#13]
Please, provide examples for SERVER_URL value at the case both client and server containers are managed by the same docker.

**Comment by dtretyakov** [comment]
@gaydenko, you could specify the same URL which you use to access TeamCity server from your browser.
If you're using docker compose to start containers you could take a look at the following samples:
https://github.com/JetBrains/teamcity-docker-samples

**Comment by gaydenko** [comment]
Aha, I see, thanks! I still guess it would be handy to add a ref to `docker-compose.yml` or/and to metntion `--link` flag of `run` agent's command.
