### ISSUE TITLE
What is the Docker Hub release process?

### ISSUE THREAD

**Issue by chris-kobrzak** [JetBrains/teamcity-docker-agent#22]
I've just pulled the Ubuntu image from Docker Hub and I noticed it is currently out of sync with the project's `master` branch.

According to the `docker images` command, the image was last published 4 weeks ago:

> jetbrains/teamcity-agent                            latest              5ae0b299f785        **4 weeks ago**         1.4GB

... and at the moment of writing this comment the [corresponding Docker file](https://github.com/JetBrains/teamcity-docker-agent/blob/master/ubuntu/Dockerfile) was last updated just over two weeks ago.

On the same note, would you guys consider Git-tagging the releases that you publish to Docker Hub?

**Comment by dtretyakov** [comment]
@chris-kobrzak, currently the `latest` tag points to 2017.2 release wave: https://github.com/JetBrains/teamcity-docker-agent/tree/Indore-2017.2.x

Changes from the `master` are available in the upcoming 2018.1 release with EAP tags.

**Comment by chris-kobrzak** [comment]
Great stuff, thanks for clarifying, @dtretyakov.
