### ISSUE TITLE
Win32 internal error 

### ISSUE THREAD

**Issue by mattmhersh** [JetBrains/teamcity-docker-agent#24]
Error running executables using Powershell.

Try running nuget restore in Powershell:

[<<==>>] Exception: The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while setting the console window title. Contact Microsoft Customer Support Services. --> No process is on the other end of the pipe

**Comment by dtretyakov** [comment]
@mattmhersh, please describe which docker image with which tag are you using? On what host OS do you start this container?

**Note**: nanoserver supports only x64 bit apps, in nanoserver-1709 powershell was removed in favor to pwsh.

**Comment by dtretyakov** [comment]
Closing as obsolete
