### ISSUE TITLE
Agent image with React/Node?

### ISSUE THREAD

**Issue by jesuissur** [JetBrains/teamcity-docker-agent#27]
Hey guys

Do you think it would be possible for you to distribute an image based on the agent image but with node and react tooling above it?

Thanks
Phil

**Comment by VladRassokhin** [comment]
Hi,
I'd suggest to use docker-in-docker feature and run your builds/tests in another docker container (via [Docker-Wrapper feature](https://confluence.jetbrains.com/display/TCDL/Docker+Wrapper)). So you'd have reproducibility on local machine.

There're no plans to include any nodejs/npm tools into official agent docker image.
Though nothing stops you from creating image you need on top of this one.
