### ISSUE TITLE
No MS Build Tools in Windows image

### ISSUE THREAD

**Issue by marchenko1985** [JetBrains/teamcity-docker-agent#28]
Will be nice if out of the box there will be Visual Studio related binaries so we can use this image to build not only dotnet core apps but also good old .net

**Comment by dtretyakov** [comment]
@mac2000, `jetbrains/teamcity-agent:latest-windowsservercore*` images are based on `microsoft/dotnet-framework-build` images, so they include MSBuild tools.

**Comment by marchenko1985** [comment]
yep seems that problem is not related, after trying to run windows based images, it seems that agent container is trying to update itself and stuck it is definitely different issues, so probably this one should be closed, thank you in advice, will try to figure out what is happening on with agent
