### ISSUE TITLE
Support for .NET Core 2.1

### ISSUE THREAD

**Issue by Kannagi77** [JetBrains/teamcity-docker-agent#30]
Any plans to support .NET Core 2.1.300?
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

**Comment by codemash-io** [comment]
Yeah, we switched all our projects to .NET 2.1 so we would love to see integration with version 2.1.

**Comment by Kannagi77** [comment]
@codemash-io BTW, you can still upgrade it manually like this:

docker exec -it tc-agent bash -c "curl -SL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-linux-x64.tar.gz --output dotnet.tar.gz && mkdir -p /usr/share/dotnet && tar -zxf dotnet.tar.gz -C /usr/share/dotnet && rm dotnet.tar.gz"

But I guess you already know it

**Comment by dtretyakov** [comment]
We'll do that. Currently you could use something like that to create a derrived docker image from `jetbrains/teamcity-agent`:
https://github.com/dotnet/dotnet-docker/blob/master/2.1/sdk/nanoserver-1709/amd64/Dockerfile

**Comment by Kannagi77** [comment]
@dtretyakov 
Thanks. For my linux container I've already solved this by patching it:
docker exec -it tc-agent bash -c "curl -SL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.300/dotnet-sdk-2.1.300-linux-x64.tar.gz --output dotnet.tar.gz && mkdir -p /usr/share/dotnet && tar -zxf dotnet.tar.gz -C /usr/share/dotnet && rm dotnet.tar.gz"

**Comment by VladRassokhin** [comment]
Proposed fix for Linux #31

**Comment by VladRassokhin** [comment]
Would be available in TeamCity 2018.1.1
