### ISSUE TITLE
how to update .net core version

### ISSUE THREAD

**Issue by lifeshortneedwhat** [JetBrains/teamcity-docker-agent#33]
The .net core version of teamcity agent docker in windows is 2.0 now.
I have a problem that how to update the .net core version to 2.1 ?
I have searched history of this repository to find any solution, then "Don't install dotnet core sdk explicitly" had been found.
Is dotnet-framework-build contains .net core ?                                   
As a beginner of docker, I'm confused to how .net core was included, so that I can't follow the same steps to update .net core.

**Comment by dtretyakov** [comment]
@lifeshortneedwhat, it's a duplicate for #30
