### ISSUE TITLE
Symbol indexing is not working

### ISSUE THREAD

**Issue by tg73** [JetBrains/teamcity-docker-agent#35]
I'm evaluating the docker agent image.  We have the symbol server feature enabled on the TC server. I'm getting build errors when using the docker agent:

```
.NET 3.5 runtime required for symbols indexing was not found on build agent.
Failed to find Source Server tools home directory. No symbol and source indexing will be performed.
```

Is there a reason that the docker image does not contain the required components? Could you add them? And how can I add them myself in the mean time?

The [documentation](https://confluence.jetbrains.com/display/TW/Symbol+Server) does not specifically cover use with the docker image.

I'm using `jetbrains/teamcity-agent:2018.1.1-windowsservercore-1803`

**Comment by dtretyakov** [comment]
@tg73, it looks like you're using outdated Symbol Server plugin version. Try downloading the latest plugin version compatible with TeamCity 2017.2+:
https://confluence.jetbrains.com/display/TW/Symbol+Server#SymbolServer-Downloaddownload

To resolve the issue with "Failed to find Source Server tools home directory. No symbol and source indexing will be performed." you need to install [Debugging Tools](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063.aspx) into container image.

Typically you could use the docker file like that:

```dockerfile
FROM jetbrains/teamcity-agent:2018.1.1-windowsservercore-1803

# Install Mercurial
RUN Invoke-WebRequest https://download.microsoft.com/download/5/A/0/5A08CEF4-3EC9-494A-9578-AB687E716C12/windowssdk/winsdksetup.exe?ocid=wdgcx1803-download-installer -OutFile winsdksetup.exe; \
    Start-Process winsdksetup.exe -Wait -ArgumentList /features + /q ; \
    Remove-Item -Force winsdksetup.exe
```

Then start teamcity build agent from the image built from this docker file.

**Comment by tg73** [comment]
I followed your suggested actions, and it's working for me now, thanks. Perhaps this information should be added to the [documentation](https://confluence.jetbrains.com/display/TW/Symbol+Server)?

**Comment by dtretyakov** [comment]
@tg73, thanks, it was added: https://github.com/JetBrains/teamcity-symbol-server#using-in-docker-containers
