### ISSUE TITLE
.NET Core 2.2

### ISSUE THREAD

**Issue by krlxgrn** [JetBrains/teamcity-docker-agent#49]
Can we get support for Core 2.2?

**Comment by vladimirpichuzhkin** [comment]
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial#linuxubuntu
Just run this:
sudo apt-get update
sudo apt-get install wget
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo add-apt-repository universe
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
