### ISSUE TITLE
Issues trying to build ubuntu Docker Image

### ISSUE THREAD

**Issue by eshantandon** [JetBrains/teamcity-docker-agent#51]
Since the shell script referenced while building dockerfile is one level up we are having issues building the docker image.
We should probably move run-docker.sh in the ubuntu folder.

**Comment by kir** [comment]
Hi, do you use `-f ubuntu/Dockerfile` for the docker build command?

**Comment by eshantandon** [comment]
Yes.

**Comment by eshantandon** [comment]
This is the error I get on the CI/CD:
**[17:57:11][Step 3/4] COPY failed: stat /var/lib/docker/tmp/docker-builder709805828/run-docker.sh: no such file or directory**
[17:57:11][Step 3/4]  ---> 82978ec795db
[17:57:11][Step 3/4] Step 10/11 : COPY run-docker.sh /services/run-docker.sh
[17:57:11][Step 3/4] Process exited with code 1
[17:57:11][Step 3/4] Process exited with code 1 (Step: Docker Build (Docker))
[17:57:11][Step 3/4] Step Docker Build (Docker) failed

**Comment by kir** [comment]
What value do you use for "Context folder:" parameter?

**Comment by eshantandon** [comment]
Its empty, 
Probably should try ./ ?

**Comment by eshantandon** [comment]
![image](https://user-images.githubusercontent.com/43542724/54543779-a385ce00-4974-11e9-940a-c9fbdd8f94d5.png)

**Comment by kir** [comment]
I believe `.` should work for this case.

**Comment by eshantandon** [comment]
Will try that.

**Comment by eshantandon** [comment]
That works. Thanks.
