### ISSUE TITLE
Why re-tag the 'minimal-agent' image?

### ISSUE THREAD

**Issue by palver123** [JetBrains/teamcity-docker-agent#53]
Hi!

I am Docker newbie and just out of curiosity I wanna ask: what is the purpose of re-tagging the image (as suggested in the [README of the repository](https://github.com/JetBrains/teamcity-docker-agent/blob/master/README.md))?

> If you need to build your own image, you need to perform the following:
>     Pull our minimal agent image and re-tag it
> 

Isn't it bad practice to create a local tag? Doesn't it prevent my docker daemon from checksumming the image in the docker registry (DockerHub) against my local copy? If you update the docker image on DockerHub I will not get the latest version if I use my own re-tagged images for building my custom agent images.

Is this a common practice when building my customized docker images based on another?

**Comment by kir** [comment]
The current Dockerfile for teamcity-agent references local teamcity-minimal-agent image, that's why you should either re-tag jetbrains/teamcity-minimal-agent image, or you should modify Dockerfile to be based on jetbrains/teamcity-minimal-agent:latest image.
