### ISSUE TITLE
Agent unable to connect to server running behind Caddy reverse proxy with Let's Encrypt certificate

### ISSUE THREAD

**Issue by NEXUS2345** [JetBrains/teamcity-docker-agent#54]
I am attempting to connect a Linux docker agent to a TeamCity 2019.1 server. The server is hosted behind a Caddy (https://caddyserver.com) reverse proxy with transparent proxying including WebSocket. The server also uses a Let's Encrypt wildcard certificate. For some reason which I am unable to grasp, the agent refuses to connect to the server.

Here is the log:
https://gist.github.com/NEXUS2345/93a56c98d346e0094d4e90e395862832

Any help is greatly appreciated.

**Comment by dmitry-treskunov** [comment]
Hi, seems you need to add the certificate to the agent JVM, see details [here](https://twitter.com/richardjfoster/status/1134169567721398272)

**Comment by NEXUS2345** [comment]
Hi Dmitry,
Thanks for the response. First, I need to mention that the link you have provided is to a tweet, not the documentation.
Second, I believe I may have already identified the cause. I have misconfigured Caddy and told it to use just the certificate rather than the full chain, so I'll correct this and see if it fixes it.
Thanks, NEXUS2345.

**Comment by dmitry-treskunov** [comment]
Oh, sorry, I posted the wrong link :) Anyway, glad that you resolved the issue!
