### ISSUE TITLE
Can we run tests on containers in build agent by installing Docker in teamcity build agent

### ISSUE THREAD

**Issue by Elangopalakrishnan** [JetBrains/teamcity-docker-agent#55]
I'm using teamcity for running automated specflow tests in build agent,
I saw that runner type - Docker and Docker Compose.
Can we run tests on containers in build agent by installing Docker in teamcity build agent.
How to run the same tests in docker container in teamcity.
Any option available in teamcity? please advice?

Thanks!

**Comment by kir** [comment]
Hi,

  You can definitely run your tests in docker if you install docker on build agents.

  You can use [Docker Compose](https://www.jetbrains.com/help/teamcity/2019.1/integrating-teamcity-with-docker.html#IntegratingTeamCitywithDocker-DockerComposeRunner) runner, [generic Docker command runner](https://www.jetbrains.com/help/teamcity/2019.1/integrating-teamcity-with-docker.html#IntegratingTeamCitywithDocker-DockerCommand) , and also [docker wrapper](https://www.jetbrains.com/help/teamcity/docker-wrapper.html), which can run .NET builds as well.

  Hope this helps,

**Comment by Elangopalakrishnan** [comment]
@kir Thanks, Will try and let you know :)
