### ISSUE TITLE
Missing fontconfig package in linux

### ISSUE THREAD

**Issue by Jarris3154** [JetBrains/teamcity-docker-agent#56]
When the code contains Excel generate, the build will fail with following error message:

![image](https://user-images.githubusercontent.com/19629719/61199871-1f6d0880-a712-11e9-9f26-f6518e149f06.png)

I guess it's because the package `fontconfig` is missing in the ubuntu.

I work with this script to install fontconfig and resolved the problem, so I strongly suggest to add the following command into the container based ubuntu.

```bash
docker exec -it {{agentContainerId}} bash
apt-get install -y fontconfig
```

Here is the link I get solutions from: https://github.com/AdoptOpenJDK/openjdk-build/issues/693

**Comment by kir** [comment]
Thanks, I've created https://youtrack.jetbrains.com/issue/TW-61230 issue in  our tracker for this task.
