### ISSUE TITLE
DOCKER_OPTS insecure-registry setting not working

### ISSUE THREAD

**Issue by overton660** [JetBrains/teamcity-docker-agent#57]
I am trying to run a docker build in an agent within the container. The docker file of my project pulls from an insecure docker registry. I have tried setting the insecure registry in the docker_opts environment variable, but am still getting the error. Hoping someone can guide me in the right direction

Here is my docker run command.
`docker run -it -e SERVER_URL="http://buildtest:880"  --privileged -e DOCKER_OPTS="--insecure-registry 10.0.4.89:2113"  -e DOCKER_IN_DOCKER=start -e AGENT_NAME="Docker-TeamCity" -v :/data/teamcity_agent/conf jetbrains/teamcity-agent`

The agent starts and connects to our agent perfectly, but I get the classic insecure registry error 'http response to an https client' I have execed into the machine and dont see a daemon.json file. Not sure if I should just mount the file, or if that would even work. Any help is appreciated.

**Comment by kir** [comment]
Hi, have you tried setting DOCKER_OPTS environment variable in your build settings, in the Parameters section of the build configuration?

**Comment by overton660** [comment]
I have not, I will try that and get back

**Comment by overton660** [comment]
I am not sure if I have the correct syntax, but what I have now is not working.

![image](https://user-images.githubusercontent.com/11725726/66337664-36805880-e905-11e9-92c0-674a50f59745.png)

Is this how to set the variable properly?

**Comment by kir** [comment]
Hi, you should add not "Docker Opts" variable in TeamCity UI, but DOCKER_OPTS, so the name would be `env.DOCKER_OPTS` and the value `--incesure-registry...`

Hope this helps,

**Comment by overton660** [comment]
Gotcha, I will give that a shot just to see if it works, but I did end up resolving the issue by setting up a revers proxy server to handle the https
