### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by apropatznpetl** [JetBrains/teamcity-docker-agent#61]
I'm trying to build the agent image using this repository (since we need .net core 3.1 sdk installed on the agent and the image from docker hub is still using 3.0.100) but the build fails at "STEP 4", presumably while installing "libc" binaries with a gzip error.
For better understanding I have attatched the [last few lines of the build log](https://github.com/JetBrains/teamcity-docker-agent/files/4076223/buildlog.txt).

As base image I tried using the minimal agent image from docker hub and one that I build on my machine following the instructions on its repository. Both were resulting in the same error message.

Please let me know if you are able to reproduce the behaviour or if I'm doing something wrong here.

Edit: Forgot to mention I'm building on Windows using docker containers. I'm aiming to build an agent running on ubuntu.

**Comment by paksv** [comment]
Hi, probably not too much I can help here with. I would recommend you to start the base container interactively and run this command directly from shell. That would make the debugging installation process much easier.
