### ISSUE TITLE
windows docker image doesn't contain powershell

### ISSUE THREAD

**Issue by abelal83** [JetBrains/teamcity-docker-agent#63]
it contains powershell core but that doesn't work with chocolatey. How can we enable classic powershell?

**Comment by JuliaResh** [comment]
@abelal83 Which tag do you use? `jetbrains/teamcity-agent:windowsservercore` should have PowerShell Desktop available. Default image for Windows is `nanoserver` which indeed has only core edition.

**Comment by abelal83** [comment]
hi @JuliaResh I was using jetbrains/teamcity-agent, I'm using jetbrains/teamcity-agent:eap-windowsservercore-1809 now which I'm hoping is OK?

**Comment by JuliaResh** [comment]
@abelal83 Yes, `jetbrains/teamcity-agent:eap-windowsservercore-1809` should have PowerSehll desktop edition available. Does it work for you?

**Comment by abelal83** [comment]
yep, thank you!
