### ISSUE TITLE
Document options that can be set in environment variables

### ISSUE THREAD

**Issue by spikyjt** [JetBrains/teamcity-docker-agent#64]
As per #14 there are various environment variables that can be used to configure the agent. Only `SERVER_URL` is documented in the README, but it would really help when getting started if they were all documented.

From what I've seen in the startup script, I assume they are:
```
SERVER_URL
AGENT_TOKEN
AGENT_NAME
OWN_ADDRESS
OWN_PORT
```
Perhaps there are others too?

In my set up, `AGENT_NAME` and `OWN_ADDRESS` were critical.

**Comment by kir** [comment]
Hi, I've added the corresponding section to https://hub.docker.com/r/jetbrains/teamcity-agent, please let me know if it faces your expectations

**Comment by spikyjt** [comment]
@kir thanks. Just one error, the `OWN_PORT` descriptions says:

> IP address build agent binds to, 9090 by default

Copy and paste error I guess? Should say:

> Port build agent binds to, 9090 by default

**Comment by kir** [comment]
@spikyjt Thanks a lot, corrected!
