### ISSUE TITLE
Issue with apt installer

### ISSUE THREAD

**Issue by sprudel79** [JetBrains/teamcity-docker-agent#65]
Hi everyone,
our Dockerfile to create a customized Teamcity Docker agents starts with the following lines:

`FROM jetbrains/teamcity-agent:latest`
`RUN apt-get update`
`...`

Trying to build the image results in the following error:

E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/

Docker version is 19.03.09 running on Linux Mint 19.3 by the way.
Is this an issue coming from the base image?
Thanks in advance.

**Comment by kir** [comment]
Hi, try inserting `USER root` before RUN instruction

Hope this helps,

**Comment by sprudel79** [comment]
Thanks @kir , it works now again.
But out of curiosity, was there any change in the base image that has caused this behaviour?

**Comment by kir** [comment]
This happens due to this change: https://youtrack.jetbrains.com/issue/TW-65785
Glad it works again for you :)

**Comment by sprudel79** [comment]
Perfect, so it's crystal clear for me now.
Thanks again for the instant support.
