### ISSUE TITLE
teamcity-agent docker image latest version jetbrains/teamcity-agent:2020.1 prevents installations as root

### ISSUE THREAD

**Issue by LennyCastaneda** [JetBrains/teamcity-docker-agent#68]
The latest docker image for teamcity-agent actually never switches users for the image build. It just stays root for all commands.

The concept of introducing the setting and running user to a non-root one was published  a couple days ago. Great concept, but it's a killer for sure for any builds that need to install dependecy tools such as .NET Octo CLI.

The problem is also that it won't allow sudo'ing to root from TeamCity Server. It doesn't work. I'm guessing that their new "buildagent" user isn't a valid sudo'er

[https://hub.docker.com/layers/jetbrains/teamcity-agent/2020.1/images/sha256-d5905e6e99e6298d69ecd0456fe5c3953d5111e0b9f9e9875a980b8168068362?context=explore](url)

**Comment by paksv** [comment]
Hi @LennyCastaneda, we are actually considering having a special tag for agent with nopasswd sudo allowed. I'll keep you posted

**Comment by paksv** [comment]
https://youtrack.jetbrains.com/issue/TW-66322
