### ISSUE TITLE
How to import GnuPG keys?

### ISSUE THREAD

**Issue by Schmazda** [JetBrains/teamcity-docker-agent#69]
I wanted to auto-release my artifacts to Maven Central and for that I need to sign these artifacts. I already created and uploaded a GnuPG key for that but I don't know how to use this key in TeamCity.

I run both TeamCity Server and Agent in Docker containers on Ubuntu 18.04.

**Comment by kir** [comment]
Hi,

 I suppose you should pass extra volume with your GPG directory when starting build agent via docker: 
-v /home/builduser/.gnupg:/home/buildagent/.gnupg

  Hope this helps,

**Comment by Schmazda** [comment]
It worked, thank you! Now I have to find out how to fix ` gpg: no default secret key: No secret key` xD
